"""memory tables

Revision ID: 0002_memory
Revises: 0001
Create Date: 2026-10-02 18:37:46.858483
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0002_memory'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('upto_message_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_summaries'))
    )
    with op.batch_alter_table('conversation_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_summaries_user_id'), ['user_id'], unique=False)

    op.create_table('graph_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('src_key', sa.String(length=240), nullable=False),
    sa.Column('rel', sa.String(length=40), nullable=False),
    sa.Column('dst_key', sa.String(length=240), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_ref', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_edges'))
    )
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_edges_dst_key'), ['dst_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_edges_src_key'), ['src_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_edges_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_edges_valid_to'), ['valid_to'], unique=False)

    op.create_table('graph_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=240), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_nodes')),
    sa.UniqueConstraint('user_id', 'key', name='uq_graph_nodes_user_key')
    )
    with op.batch_alter_table('graph_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_nodes_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_nodes_user_id'), ['user_id'], unique=False)

    op.create_table('profile_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_cards')),
    sa.UniqueConstraint('user_id', 'version', name='uq_profile_cards_user_version')
    )
    with op.batch_alter_table('profile_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_cards_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_cards_user_id'))

    op.drop_table('profile_cards')
    with op.batch_alter_table('graph_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_nodes_user_id'))
        batch_op.drop_index(batch_op.f('ix_graph_nodes_key'))

    op.drop_table('graph_nodes')
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_edges_valid_to'))
        batch_op.drop_index(batch_op.f('ix_graph_edges_user_id'))
        batch_op.drop_index(batch_op.f('ix_graph_edges_src_key'))
        batch_op.drop_index(batch_op.f('ix_graph_edges_dst_key'))

    op.drop_table('graph_edges')
    with op.batch_alter_table('conversation_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_summaries_user_id'))

    op.drop_table('conversation_summaries')
    # ### end Alembic commands ###
